/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author User
 */
public class FinalView_JavaRound2 extends javax.swing.JFrame {

    /**
     * Creates new form FinalView_JavaRound2
     */
    public FinalView_JavaRound2() {
        initComponents();
        setDefaultCloseOperation(0);
        Login l=new Login();
        this.setTitle("Team : "+l.teamName+"- Round 2 result");
        tablindcode.setEditable(false);
    }

     public void View(JLabel i1, JLabel i2, JTextArea blindcode, JLabel i3 )
    {
        tablindcode.setText(blindcode.getText());
        part1.setIcon(i1.getIcon());
        part2.setIcon(i2.getIcon());
        part3.setIcon(i3.getIcon());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        part3 = new javax.swing.JLabel();
        part1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablindcode = new javax.swing.JTextArea();
        part2 = new javax.swing.JLabel();
        finish = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        part3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/images/final_submit/part3.png"))); // NOI18N
        jPanel1.add(part3);
        part3.setBounds(30, 530, 368, 154);

        part1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/images/final_submit/part1.png"))); // NOI18N
        jPanel1.add(part1);
        part1.setBounds(30, 10, 368, 154);

        tablindcode.setColumns(20);
        tablindcode.setRows(5);
        jScrollPane1.setViewportView(tablindcode);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 350, 370, 170);

        part2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/images/final_submit/part2.png"))); // NOI18N
        jPanel1.add(part2);
        part2.setBounds(30, 180, 368, 154);

        finish.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        finish.setText("FINISH");
        finish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                finishActionPerformed(evt);
            }
        });
        jPanel1.add(finish);
        finish.setBounds(410, 420, 110, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/images/extras/final view.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -6, 550, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 546, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void finishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_finishActionPerformed
        // TODO add your handling code here:
        StopWatch ob=new StopWatch();
        ob.t.stop();
        finish.setVisible(false);
        try {
            FileWriter saveTime= new FileWriter(new File("c:\\SudoKodia\\stop watch.doc"));
            
            saveTime.write(ob.currTime);
            //JOptionPane.showMessageDialog(this, "stop");
            saveTime.close();
                  
        } catch (IOException ex) {
            Logger.getLogger(FinalView_JavaRound2.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "error");
        }
        new Evaluation().setVisible(true);
    }//GEN-LAST:event_finishActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalView_JavaRound2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalView_JavaRound2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalView_JavaRound2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalView_JavaRound2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalView_JavaRound2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton finish;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel part1;
    private javax.swing.JLabel part2;
    private javax.swing.JLabel part3;
    private javax.swing.JTextArea tablindcode;
    // End of variables declaration//GEN-END:variables
}
