/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

import java.awt.Image;
import java.awt.TextArea;
import java.awt.Toolkit;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author User
 */
public class FinalView_CRound1 extends javax.swing.JFrame {

    /**
     * Creates new form FinalView
     */
    public FinalView_CRound1() {
        initComponents();
        star();
        setDefaultCloseOperation(0);
        Login l=new Login();
        this.setTitle("Team : "+l.teamName+"- Round 1 result");
        this.setVisible(false);
        tablindcode.setEditable(false);
        
    }
    
    public void star(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/javaapplication2/images/extras/icon.png")));
    }
    public void View(JLabel i1, JLabel i2, JTextArea blindcode, JLabel i3 )
    {
        tablindcode.setText(blindcode.getText());
        part1.setIcon(i1.getIcon());
        part2.setIcon(i2.getIcon());
        part3.setIcon(i3.getIcon());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        part1 = new javax.swing.JLabel();
        part2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablindcode = new javax.swing.JTextArea();
        part3 = new javax.swing.JLabel();
        round2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        part1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/images/final_submit/part1.png"))); // NOI18N
        jPanel1.add(part1);
        part1.setBounds(30, 10, 368, 154);

        part2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/images/final_submit/part2.png"))); // NOI18N
        jPanel1.add(part2);
        part2.setBounds(30, 180, 368, 154);

        tablindcode.setColumns(20);
        tablindcode.setRows(5);
        jScrollPane1.setViewportView(tablindcode);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(30, 340, 370, 190);

        part3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/images/final_submit/part3.png"))); // NOI18N
        jPanel1.add(part3);
        part3.setBounds(30, 530, 368, 154);

        round2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        round2.setText("Round 2");
        round2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                round2ActionPerformed(evt);
            }
        });
        jPanel1.add(round2);
        round2.setBounds(460, 430, 80, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/images/extras/final view.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 550, 740);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 549, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 736, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void round2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_round2ActionPerformed
        // TODO add your handling code here:
        new RoundTwoQuestionsC().setVisible(true);
        round2.setVisible(false);
    }//GEN-LAST:event_round2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalView_CRound1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalView_CRound1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalView_CRound1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalView_CRound1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinalView_CRound1().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel part1;
    private javax.swing.JLabel part2;
    private javax.swing.JLabel part3;
    private javax.swing.JButton round2;
    private javax.swing.JTextArea tablindcode;
    // End of variables declaration//GEN-END:variables
}
