/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author User
 */
public class LanguageSelection extends javax.swing.JFrame {

    /**
     * Creates new form LanguageSelection
     */
    public LanguageSelection() 
    {
        initComponents();
        star();
        this.setTitle("SudoKodia-   A Blind Coding Puzzle...");
        setDefaultCloseOperation(0);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
       setBounds(0,0,screenSize.width, screenSize.height);
       setVisible(true);
        
    }

    public void star(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/javaapplication2/images/extras/icon.png")));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        next = new javax.swing.JButton();
        langc = new javax.swing.JRadioButton();
        langjava = new javax.swing.JRadioButton();
        logo = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(null);

        next.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        next.setText("Next");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        jPanel1.add(next);
        next.setBounds(850, 540, 150, 40);

        langc.setBackground(new java.awt.Color(163, 144, 112));
        buttonGroup1.add(langc);
        langc.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        langc.setText("C");
        langc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                langcActionPerformed(evt);
            }
        });
        jPanel1.add(langc);
        langc.setBounds(380, 270, 150, 160);

        langjava.setBackground(new java.awt.Color(163, 144, 112));
        buttonGroup1.add(langjava);
        langjava.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        langjava.setText("JAVA");
        langjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                langjavaActionPerformed(evt);
            }
        });
        jPanel1.add(langjava);
        langjava.setBounds(690, 270, 140, 160);

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/images/extras/login_logo.png"))); // NOI18N
        jPanel1.add(logo);
        logo.setBounds(60, 0, 330, 280);

        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/images/extras/title.png"))); // NOI18N
        jPanel1.add(title);
        title.setBounds(320, 20, 690, 220);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/images/extras/lang select.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(310, 160, 730, 610);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1265, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 858, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
        
        
        if(langc.isSelected())
        {
            this.setVisible(false);
            new RoundOneQuestionsC().setVisible(true);
           
        }
        if(langjava.isSelected())
        {
           this.setVisible(false);
            new RoundOneQuestionsJava().setVisible(true);
            
        }
        
    }//GEN-LAST:event_nextActionPerformed

    private void langjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_langjavaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_langjavaActionPerformed

    private void langcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_langcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_langcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LanguageSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LanguageSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LanguageSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LanguageSelection.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LanguageSelection().setVisible(true);
                
            }
        });
    }
    static int count=0;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton langc;
    private javax.swing.JRadioButton langjava;
    private javax.swing.JLabel logo;
    private javax.swing.JButton next;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
