/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;


/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        star();
        this.setTitle("SudoKodia-   A Blind Coding Puzzle...");
        setDefaultCloseOperation(0);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        //setBounds(0,0,screenSize.width, screenSize.height);
        setResizable(false);
        
        
    }

    public void star(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/javaapplication2/images/extras/icon.png")));
    }
    public void showTimer()
    {
        new StopWatch().setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
  
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        login = new javax.swing.JLabel();
        pass = new javax.swing.JLabel();
        tflogin = new javax.swing.JTextField();
        bLogin = new javax.swing.JButton();
        tfpassword = new javax.swing.JPasswordField();
        title = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        login.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Login Id:");
        jPanel1.add(login);
        login.setBounds(410, 330, 80, 20);

        pass.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pass.setForeground(new java.awt.Color(255, 255, 255));
        pass.setText("Password:");
        jPanel1.add(pass);
        pass.setBounds(410, 390, 90, 20);

        tflogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfloginActionPerformed(evt);
            }
        });
        jPanel1.add(tflogin);
        tflogin.setBounds(520, 330, 120, 20);

        bLogin.setFont(new java.awt.Font("Tekton Pro Cond", 1, 14)); // NOI18N
        bLogin.setText("Login");
        bLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLoginActionPerformed(evt);
            }
        });
        jPanel1.add(bLogin);
        bLogin.setBounds(530, 470, 90, 23);

        tfpassword.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPanel1.add(tfpassword);
        tfpassword.setBounds(520, 390, 120, 20);

        title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/images/extras/title.png"))); // NOI18N
        title.setText("jLabel1");
        jPanel1.add(title);
        title.setBounds(360, 50, 580, 200);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/images/extras/login_logo.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(70, 0, 360, 290);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/images/extras/LoginPageDesign.png"))); // NOI18N
        bg.setText("jLabel3");
        jPanel1.add(bg);
        bg.setBounds(-100, -10, 1280, 610);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 579, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfloginActionPerformed
        // TODO add your handling code here:
        tflogin.setText(null);
    }//GEN-LAST:event_tfloginActionPerformed

    private void bLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLoginActionPerformed
        // TODO add your handling code here:
        if(tflogin.getText().equals("choxx") && tfpassword.getText().equals("choxx") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team1") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team2") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team3") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team4") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team5") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team6") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team7") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team8") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team9") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team10") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team11") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team12") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team13") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team14") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team15") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team16") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team17") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team18") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team19") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team20") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team21") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team22") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team23") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team24") && tfpassword.getText().equals("techfeast") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team25") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
            if(tflogin.getText().equals("team26") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team27") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team28") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team29") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team30") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team31") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team32") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team33") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team34") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
            if(tflogin.getText().equals("team35") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team36") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team37") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team38") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team39") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team40") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team41") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team42") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team43") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team44") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team45") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team46") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team47") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team48") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team49") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team50") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team51") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team52") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team53") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team54") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team55") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team56") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team57") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team58") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team59") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team60") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team61") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team62") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team63") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team64") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team65") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team66") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team67") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team68") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team69") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team70") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team71") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team72") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team73") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team74") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team75") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team76") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team77") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team78") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team79") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team80") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team81") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team82") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team83") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team84") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team85") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team86") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team87") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team88") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team89") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }else
        if(tflogin.getText().equals("team90") && tfpassword.getText().equals("techfeast2k14") )
        {
            teamName=tflogin.getText();
            this.setVisible(false);
            
            new LanguageSelection().setVisible(true);
           showTimer();
            
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Invalid login id or password!!!");
        }   
    }//GEN-LAST:event_bLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        //java.awt.EventQueue.invokeLater(new Runnable() {
          //  public void run() {
              new Login().setVisible(true);
            //}
        //});
    }

    static String teamName;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bLogin;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel login;
    private javax.swing.JLabel pass;
    public javax.swing.JTextField tflogin;
    private javax.swing.JPasswordField tfpassword;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
