/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class Run extends javax.swing.JFrame {

    /**
     * Creates new form Run
     */
    public Run() {
        initComponents();
        star();
        this.setVisible(true);
        this.setTitle("Go For it.. See what you have Coded... (Blind Coded..) ");
        setDefaultCloseOperation(0);
        setResizable(false);
    }

    public void star(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/javaapplication2/images/extras/icon.png")));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        runRound1 = new javax.swing.JButton();
        runRound2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(72, 119, 255));
        jPanel1.setLayout(null);

        runRound1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        runRound1.setText("Round 1");
        runRound1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runRound1ActionPerformed(evt);
            }
        });
        jPanel1.add(runRound1);
        runRound1.setBounds(250, 260, 110, 30);

        runRound2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        runRound2.setText("Round 2");
        runRound2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                runRound2ActionPerformed(evt);
            }
        });
        jPanel1.add(runRound2);
        runRound2.setBounds(250, 320, 110, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Hit the button to compile & execute your complete program..");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(50, 70, 560, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/images/extras/run.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(320, 210, 330, 310);

        jLabel3.setFont(new java.awt.Font("New MOTOR", 1, 18)); // NOI18N
        jLabel3.setText("Let's Check your coding..!!");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 20, 500, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/images/extras/run all best.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(-120, 120, 600, 260);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Note: In the next window, just type the 'execute'+'round number' & hit ENTER");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 410, 470, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 658, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void runRound1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runRound1ActionPerformed
        // TODO add your handling code here:
        
        File addr= new File("c:/SudoKodia");
        String [] command= new String[2];
        command[0]="cmd /c start";
        command[1]="execute1.cmd";
       // command[2]="javac test.java";
       // command[3]="pause";
       // command[4]="java test";
        try {
            Process p= Runtime.getRuntime().exec("cmd /c start",null,addr);
            //ProcessBuilder x= new ProcessBuilder(command);
            
            //Runtime.getRuntime().
                    
        } catch (IOException ex) {
            Logger.getLogger(Run.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_runRound1ActionPerformed

    private void runRound2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_runRound2ActionPerformed
        // TODO add your handling code here:
        File addr= new File("c:/SudoKodia");
        try {
            Process p= Runtime.getRuntime().exec("cmd /c start", null, addr);
        } catch (IOException ex) {
            Logger.getLogger(Run.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_runRound2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Run.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Run.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Run.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Run.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Run().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton runRound1;
    private javax.swing.JButton runRound2;
    // End of variables declaration//GEN-END:variables
}
