/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

import java.awt.Toolkit;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author User
 */
public class TeamInfo extends javax.swing.JFrame {

    /**
     * Creates new form TeamInfo
     */
    public TeamInfo() {
        initComponents();
        this.setTitle("Details");
        star();
        setDefaultCloseOperation(0);
        setResizable(false);
        
    }

    public void star(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/javaapplication2/images/extras/icon.png")));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        name1 = new javax.swing.JTextField();
        name2 = new javax.swing.JTextField();
        branch1 = new javax.swing.JTextField();
        branch2 = new javax.swing.JTextField();
        college1 = new javax.swing.JTextField();
        college2 = new javax.swing.JTextField();
        year1 = new javax.swing.JTextField();
        year2 = new javax.swing.JTextField();
        contnum1 = new javax.swing.JTextField();
        contnum2 = new javax.swing.JTextField();
        submit = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(89, 69, 196));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Enter your Team Details...");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(160, 10, 550, 110);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Names:");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(140, 170, 80, 40);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Branch:");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(140, 240, 100, 30);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("College:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(140, 300, 80, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Year:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(160, 350, 70, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Contact No. :");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(100, 400, 140, 40);

        name1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                name1ActionPerformed(evt);
            }
        });
        jPanel1.add(name1);
        name1.setBounds(230, 180, 180, 20);
        jPanel1.add(name2);
        name2.setBounds(510, 180, 170, 20);
        jPanel1.add(branch1);
        branch1.setBounds(230, 240, 180, 20);
        jPanel1.add(branch2);
        branch2.setBounds(510, 240, 170, 20);
        jPanel1.add(college1);
        college1.setBounds(230, 300, 180, 20);
        jPanel1.add(college2);
        college2.setBounds(510, 300, 170, 20);
        jPanel1.add(year1);
        year1.setBounds(230, 360, 180, 20);
        jPanel1.add(year2);
        year2.setBounds(510, 360, 170, 20);
        jPanel1.add(contnum1);
        contnum1.setBounds(230, 410, 180, 20);
        jPanel1.add(contnum2);
        contnum2.setBounds(510, 410, 170, 20);

        submit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        submit.setText("Continue");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel1.add(submit);
        submit.setBounds(390, 460, 130, 40);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Player 1");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(280, 130, 100, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Player 2");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(560, 130, 100, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 818, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void name1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_name1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_name1ActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        try {
            // TODO add your handling code here:
            File dir=new File("c:/SudoKodia Team Details");
            dir.mkdir();
            info= new FileWriter(dir+"/Team Info.doc");
            info.write("NAMES:    "+name1.getText()+"\t\t"+name2.getText());
            info.write("\n\nBRANCH:   "+branch1.getText()+"\t\t"+branch2.getText());
            info.write("\n\nCOLLEGE:  "+college1.getText()+"\t\t"+college2.getText());
            info.write("\n\nYEAR    : "+year1.getText()+"\t\t"+year2.getText());
            info.write("\n\nCONT. NO.:"+contnum1.getText()+"\t\t"+contnum2.getText());
            info.close();
            this.setVisible(false);
        } catch (IOException ex) {
            Logger.getLogger(TeamInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
        
         new Login().setVisible(true);
    }//GEN-LAST:event_submitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeamInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeamInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeamInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeamInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeamInfo().setVisible(true);
            }
        });
    }

    static FileWriter info;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField branch1;
    private javax.swing.JTextField branch2;
    private javax.swing.JTextField college1;
    private javax.swing.JTextField college2;
    private javax.swing.JTextField contnum1;
    private javax.swing.JTextField contnum2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField name1;
    private javax.swing.JTextField name2;
    private javax.swing.JButton submit;
    private javax.swing.JTextField year1;
    private javax.swing.JTextField year2;
    // End of variables declaration//GEN-END:variables
}
