/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaapplication2;

import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.Timer;

/**
 *
 * @author User
 */
public class ViewCodeTimer extends javax.swing.JFrame {

    /**
     * Creates new form ViewCode
     */
    static int minutes=4,

    /**
     * Creates new form ViewCodeTimer
     */
    seconds=60;
    public ViewCodeTimer() {
        initComponents();
        star();
        //setBounds(50, 50, 200, 300);
        setDefaultCloseOperation(0);
        this.setTitle("View Blind Code");
        setResizable(false);
        
       
    }
   public void star(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/javaapplication2/images/extras/icon.png")));
    }
    
    public void show(JLabel p1,JLabel p2,JTextArea code, JLabel p3)
    {
        part1.setIcon(p1.getIcon());
        part2.setIcon(p2.getIcon());
        part3.setIcon(p3.getIcon());
        tablindcode.setText(code.getText());
        tablindcode.setEditable(false);
        t=new Timer(1000, new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                seconds--;
                
                if(seconds==0)
                {
                    seconds=60;
                    minutes=minutes-1;
                }
                if(minutes<0)
                {
                    t.stop();
                    hideWindow();
                    
                    
                }
                time.setText((minutes)+":"+(seconds));
            }     
        });
         t.start();
        
    }
    public void hideWindow(){
        this.setVisible(false);
        seconds=60;
        minutes=4;
        dispose();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        time = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablindcode = new javax.swing.JTextArea();
        close = new javax.swing.JButton();
        part1 = new javax.swing.JLabel();
        part2 = new javax.swing.JLabel();
        part3 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        time.setBackground(new java.awt.Color(102, 102, 255));
        time.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        time.setText("5:00");
        jPanel1.add(time);
        time.setBounds(440, 190, 150, 70);

        tablindcode.setColumns(20);
        tablindcode.setRows(5);
        tablindcode.setOpaque(false);
        jScrollPane1.setViewportView(tablindcode);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 380, 370, 140);

        close.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel1.add(close);
        close.setBounds(390, 590, 130, 30);

        part1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/images/final_submit/part1.png"))); // NOI18N
        jPanel1.add(part1);
        part1.setBounds(20, 40, 368, 154);

        part2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/images/final_submit/part2.png"))); // NOI18N
        jPanel1.add(part2);
        part2.setBounds(20, 210, 368, 154);

        part3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/images/final_submit/part3.png"))); // NOI18N
        jPanel1.add(part3);
        part3.setBounds(20, 540, 368, 154);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication2/images/extras/viewCodeTimer_bg.jpg"))); // NOI18N
        jPanel1.add(bg);
        bg.setBounds(-1120, 0, 1660, 840);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 534, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 776, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        seconds=60;
        minutes=4;
        t.stop();
        dispose();
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCodeTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCodeTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCodeTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCodeTimer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCodeTimer().setVisible(true);
            }
        });
    }

    Timer t;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg;
    private javax.swing.JButton close;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel part1;
    private javax.swing.JLabel part2;
    private javax.swing.JLabel part3;
    private javax.swing.JTextArea tablindcode;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
